import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { format } from 'date-fns';

const styles = StyleSheet.create({
  page: {
    padding: 30,
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  table: {
    display: 'table',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    flexDirection: 'row',
  },
  tableCol: {
    width: '25%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCell: {
    margin: 5,
    fontSize: 12,
  },
});

interface PDFReportProps {
  title: string;
  data: any[];
  columns: { key: string; label: string }[];
  filters?: Record<string, any>;
  generatedBy: string;
}

const PDFReport: React.FC<PDFReportProps> = ({
  title,
  data,
  columns,
  filters,
  generatedBy,
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text>{title}</Text>
      </View>

      {filters && (
        <View style={styles.section}>
          <Text>Filters:</Text>
          {Object.entries(filters).map(([key, value]) => (
            <Text key={key}>
              {key}: {value}
            </Text>
          ))}
        </View>
      )}

      <View style={styles.table}>
        <View style={styles.tableRow}>
          {columns.map((column) => (
            <View key={column.key} style={styles.tableCol}>
              <Text style={styles.tableCell}>{column.label}</Text>
            </View>
          ))}
        </View>

        {data.map((row, index) => (
          <View key={index} style={styles.tableRow}>
            {columns.map((column) => (
              <View key={column.key} style={styles.tableCol}>
                <Text style={styles.tableCell}>{row[column.key]}</Text>
              </View>
            ))}
          </View>
        ))}
      </View>

      <View style={styles.section}>
        <Text>Generated by: {generatedBy}</Text>
        <Text>Date: {format(new Date(), 'PPP')}</Text>
      </View>
    </Page>
  </Document>
);

export default PDFReport;